// Generated by ts-to-zod
import { z } from "zod";

export const altStoreScreenshotSchema = z.union([z.string(), z.object({
        imageURL: z.string(),
        width: z.number().optional(),
        height: z.number().optional()
    })]);

export const altStoreAppVersionSchema = z.object({
    version: z.string(),
    buildVersion: z.string().optional(),
    marketingVersion: z.string().optional(),
    date: z.string(),
    downloadURL: z.string(),
    localizedDescription: z.string().optional(),
    size: z.number().optional(),
    minOSVersion: z.string().optional(),
    maxOSVersion: z.string().optional()
});

export const altStoreAppPermissionsSchema = z.object({
    entitlements: z.array(z.string()).optional(),
    privacy: z.record(z.string(), z.string()).optional()
});

export const altStoreAppSchema = z.object({
    name: z.string(),
    bundleIdentifier: z.string(),
    developerName: z.string(),
    subtitle: z.string().optional(),
    localizedDescription: z.string(),
    iconURL: z.string(),
    tintColor: z.string().optional(),
    screenshots: z.union([z.array(altStoreScreenshotSchema), z.record(z.union([z.literal("iphone"), z.literal("ipad")]), z.array(altStoreScreenshotSchema))]).optional(),
    versions: z.array(altStoreAppVersionSchema),
    appPermissions: altStoreAppPermissionsSchema.optional(),
    category: z.union([z.literal("developer"), z.literal("entertainment"), z.literal("games"), z.literal("lifestyle"), z.literal("other"), z.literal("photo-video"), z.literal("social"), z.literal("utilities")]).optional()
});

export const altStoreNewsItemSchema = z.object({
    title: z.string(),
    identifier: z.string(),
    caption: z.string().optional(),
    date: z.string(),
    tintColor: z.string().optional(),
    imageURL: z.string().optional(),
    notify: z.boolean().optional(),
    url: z.string().optional(),
    appID: z.string().optional()
});

export const altStoreSourceSchema = z.object({
    name: z.string(),
    subtitle: z.string().optional(),
    description: z.string().optional(),
    iconURL: z.string().optional(),
    headerURL: z.string().optional(),
    website: z.string().optional(),
    tintColor: z.string().optional(),
    featuredApps: z.array(z.string()).optional(),
    apps: z.array(altStoreAppSchema),
    news: z.array(altStoreNewsItemSchema).optional()
});
